name: Lint

on:
  pull_request:
    branches:
      - master

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install flake8

      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.6

      - name: List with flake8
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [ "${file: -3}" == ".py" ]
            then
              echo "flake8 --filename=./$file"
              flake8 --filename=./$file
            fi
          done

      # - name: Lint with flake8
      #   run: flake8 --filename=./testing-code/test4.py

  # - name: Run linters
  #   uses: wearerequired/lint-action@v2
  #   with:
  #     black: false
  #     flake8: true
